### ISSUE TITLE
Notification on New Comment in Participating Issue or Pull Request

### ISSUE THREAD

**Issue by xanderdunn** [frapontillo/hubot-github-notify#8]
Feature request: 

Right now hubot-github-notify sends notifications in these situations:
- An issue or pull request is assigned to that person
- A comment is posted anywhere with an @mention of that person

However, we'd also like to receive a notification when a comment is added to an issue or pull request that I'm "interested" in.  Trivially, this would be a notification for any issue or pull request that is assigned to me.  Optimally, this would be a notification for any issue or pull request where I'm listed as a participant (It's an opt in/out list in the right-hand column of each issue on GitHub).

**Comment by frapontillo** [comment]
Sorry @xanderdunn, I am no longer actively developing this project, but I will accept PRs.
